#!/usr/bin/env ruby

class ProjectCompletion
  def initialize(command)
    @command = command
  end
  
  def matches
    sources.select do |task|
      task[0, typed.length] == typed
    end
  end
  
  def typed
    @command[/\s(.+?)$/, 1] || ''
  end
  
  def sources
    `ls ~/source/`.split(/\n/)
  end
end

puts ProjectCompletion.new(ENV["COMP_LINE"]).matches
exit 0
